### ISSUE TITLE
Version pinning cryptography causes dependency conflicts

### ISSUE THREAD

**Issue by jorge-gasca** [soroco/pyce#12]
Example conflict when installing pyce 1.0.0 and paramiko through pipenv:
`Could not find a version that matches cryptography==2.1.4,>=2.2.`

Could we change the strict version to `>=2.1.4, <3.0.0`?

**Comment by jorge-gasca** [comment]
I was assuming that they followed semantic versioning, but according to the [cryptography docs](https://cryptography.io/en/latest/api-stability/), 2.2 could break compatibility. We should set up some sort of CI then. @aaronsewall

**Comment by theonewolf** [comment]
@jorge-gasca semantic versioning does not say anything about the outcome of **integration tests**.  It _claims_ backwards compatibility to a certain API.  Occasionally, even that claim is violated by developers for various reasons.  And a version number is not enough to communicate such subtleties downstream.

In an ideal world, yes, it would pass integration tests.  In reality, you can not say anything principled about a derived product when an upstream version changes even a single bit within their product.

If we consider computer programs as proofs, which they are as mathematical objects (https://en.wikipedia.org/wiki/Curry%E2%80%93Howard_correspondence), you've just changed the proof without properly type checking it.

I prefer sound(er) engineering.  We aren't quite as thorough as a proof, but at least it passes the tests we'd care about if we get CI in place.

So, even for semantically versioned libraries, I would only trust versions that we have CI for, and passing CI.

I think I'd be happy for now if the `demo.sh` script continued working across various versions of the `cryptography` library.

**Comment by theonewolf** [comment]
I agree on the ideal for supporting 3.6 and 3.7 at the same time, but unless we have better CI or more resources we can't right now.

For the time being, closing as WONTFIX.
